[2023-11-25T20:28:09.458+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-25T20:28:09.469+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-25T20:28:09.470+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T20:28:09.486+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-24 00:00:00+00:00
[2023-11-25T20:28:09.491+0000] {standard_task_runner.py:57} INFO - Started process 134 to run task
[2023-11-25T20:28:09.496+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpswa5hqq4']
[2023-11-25T20:28:09.499+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask transform
[2023-11-25T20:28:09.548+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:28:09.640+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-11-25T20:28:10.098+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 36, in transform_data
    data = prep_data(data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 51, in prep_data
    data['name'] = data['Name'].str.replace("*","",regex=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Name'
[2023-11-25T20:28:10.113+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231124T000000, start_date=20231125T202809, end_date=20231125T202810
[2023-11-25T20:28:10.126+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task transform ('Name'; 134)
[2023-11-25T20:28:10.159+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-25T20:28:10.191+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26T00:23:10.921+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T00:23:10.934+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T00:23:10.935+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T00:23:10.958+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-24 00:00:00+00:00
[2023-11-26T00:23:10.965+0000] {standard_task_runner.py:57} INFO - Started process 190 to run task
[2023-11-26T00:23:10.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpq_9nr9u3']
[2023-11-26T00:23:10.974+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask transform
[2023-11-26T00:23:11.036+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [running]> on host decfc1fe5c09
[2023-11-26T00:23:11.132+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-11-26T00:23:11.900+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T00:23:11.913+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231124T000000, start_date=20231126T002310, end_date=20231126T002311
[2023-11-26T00:23:11.952+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T00:23:11.972+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T01:53:47.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T01:53:47.414+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T01:53:47.415+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T01:53:47.429+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-24 00:00:00+00:00
[2023-11-26T01:53:47.436+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2023-11-26T01:53:47.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpaaw1j2rw']
[2023-11-26T01:53:47.444+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask transform
[2023-11-26T01:53:47.520+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T01:53:47.610+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-11-26T01:53:48.328+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T01:53:48.339+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231124T000000, start_date=20231126T015347, end_date=20231126T015348
[2023-11-26T01:53:48.384+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T01:53:48.409+0000] {taskinstance.py:2778} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:44:50.292+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T02:44:50.307+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26T02:44:50.308+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T02:44:50.326+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-24 00:00:00+00:00
[2023-11-26T02:44:50.335+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2023-11-26T02:44:50.340+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpx24ksi5c']
[2023-11-26T02:44:50.345+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask transform
[2023-11-26T02:44:50.418+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:44:50.547+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-11-26T02:45:00.360+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:45:00.373+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231124T000000, start_date=20231126T024450, end_date=20231126T024500
[2023-11-26T02:45:00.411+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:45:00.437+0000] {taskinstance.py:2778} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2023-12-17T15:13:57.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-12-17T15:13:57.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-12-17T15:13:57.489+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-17T15:13:57.517+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-24 00:00:00+00:00
[2023-12-17T15:13:57.538+0000] {standard_task_runner.py:57} INFO - Started process 704 to run task
[2023-12-17T15:13:57.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp78bvrwjq']
[2023-12-17T15:13:57.577+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask transform
[2023-12-17T15:13:57.689+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-24T00:00:00+00:00 [running]> on host 7f0547651eb4
[2023-12-17T15:13:57.861+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-12-17T15:14:14.906+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-17T15:14:15.040+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231124T000000, start_date=20231217T151357, end_date=20231217T151415
[2023-12-17T15:14:15.456+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-17T15:14:15.575+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
