[2023-11-24T21:55:20.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-24T21:55:20.380+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-24T21:55:20.381+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T21:55:20.607+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-24T21:55:20.620+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2023-11-24T21:55:20.627+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmprkenh1gr']
[2023-11-24T21:55:20.633+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask extract
[2023-11-24T21:55:20.695+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host 30eca782d34c
[2023-11-24T21:55:20.781+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-24T21:55:21.724+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/extract.py", line 35, in extract_data
    storage_client = storage.Client('oceanic-hangout-406022')
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 172, in __init__
    super(Client, self).__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/client/__init__.py", line 321, in __init__
    Client.__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/client/__init__.py", line 178, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File opt/***/dags/etl_scripts/oceanic-hangout-406022-fd958fa4d302.json was not found.
[2023-11-24T21:55:21.737+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231124T215520, end_date=20231124T215521
[2023-11-24T21:55:21.752+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task extract (File opt/***/dags/etl_scripts/oceanic-hangout-406022-fd958fa4d302.json was not found.; 216)
[2023-11-24T21:55:21.775+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T21:55:21.798+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-24T23:02:16.991+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-24T23:02:17.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-24T23:02:17.020+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T23:02:17.057+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-24T23:02:17.065+0000] {standard_task_runner.py:57} INFO - Started process 122 to run task
[2023-11-24T23:02:17.074+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp7y5f8nu0']
[2023-11-24T23:02:17.080+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask extract
[2023-11-24T23:02:17.217+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host 69a30b58663a
[2023-11-24T23:02:17.425+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-24T23:02:18.528+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-24T23:02:18.546+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231124T230216, end_date=20231124T230218
[2023-11-24T23:02:18.597+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T23:02:18.631+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-25T00:37:42.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T00:37:42.525+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T00:37:42.525+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-25T00:37:42.542+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-25T00:37:42.551+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2023-11-25T00:37:42.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpfhte27cv']
[2023-11-25T00:37:42.562+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask extract
[2023-11-25T00:37:42.624+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host 8e76b4343da0
[2023-11-25T00:37:42.721+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-25T00:37:43.683+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T00:37:43.695+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231125T003742, end_date=20231125T003743
[2023-11-25T00:37:43.742+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T00:37:43.762+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-25T20:49:18.447+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T20:49:18.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T20:49:18.523+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-25T20:49:18.557+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-25T20:49:18.575+0000] {standard_task_runner.py:57} INFO - Started process 494 to run task
[2023-11-25T20:49:18.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpaod68b19']
[2023-11-25T20:49:18.646+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask extract
[2023-11-25T20:49:18.727+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:49:18.819+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-25T20:49:19.761+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T20:49:19.774+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231125T204918, end_date=20231125T204919
[2023-11-25T20:49:19.805+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T20:49:19.828+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:23:34.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T02:23:34.155+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T02:23:34.156+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-26T02:23:34.171+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-26T02:23:34.177+0000] {standard_task_runner.py:57} INFO - Started process 773 to run task
[2023-11-26T02:23:34.182+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp_v3pl4dz']
[2023-11-26T02:23:34.186+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask extract
[2023-11-26T02:23:34.240+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T02:23:34.457+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-26T02:23:35.311+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:23:35.324+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231126T022334, end_date=20231126T022335
[2023-11-26T02:23:35.352+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:23:35.384+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:51:23.952+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T02:51:23.963+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T02:51:23.964+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-26T02:51:23.978+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-23 00:00:00+00:00
[2023-11-26T02:51:23.985+0000] {standard_task_runner.py:57} INFO - Started process 469 to run task
[2023-11-26T02:51:23.988+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp59mol82h']
[2023-11-26T02:51:23.992+0000] {standard_task_runner.py:85} INFO - Job 89: Subtask extract
[2023-11-26T02:51:24.046+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-23T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:51:24.135+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-26T02:51:25.216+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:51:25.228+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231123T000000, start_date=20231126T025123, end_date=20231126T025125
[2023-11-26T02:51:25.254+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:51:25.286+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
