[2023-11-25T20:27:49.642+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-25T20:27:50.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-25T20:27:50.141+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T20:27:50.189+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-22 00:00:00+00:00
[2023-11-25T20:27:50.208+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-11-25T20:27:50.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmply1ofw4t']
[2023-11-25T20:27:50.221+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask transform
[2023-11-25T20:27:50.310+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:27:50.443+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-11-25T20:27:50.889+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 36, in transform_data
    data = prep_data(data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 51, in prep_data
    data['name'] = data['Name'].str.replace("*","",regex=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Name'
[2023-11-25T20:27:50.921+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231122T000000, start_date=20231125T202749, end_date=20231125T202750
[2023-11-25T20:27:50.938+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task transform ('Name'; 114)
[2023-11-25T20:27:50.968+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-25T20:27:50.997+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26T00:22:51.982+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T00:22:51.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T00:22:51.996+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T00:22:52.013+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-22 00:00:00+00:00
[2023-11-26T00:22:52.019+0000] {standard_task_runner.py:57} INFO - Started process 172 to run task
[2023-11-26T00:22:52.023+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp_r35qi9u']
[2023-11-26T00:22:52.028+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask transform
[2023-11-26T00:22:52.097+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [running]> on host decfc1fe5c09
[2023-11-26T00:22:52.213+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-11-26T00:22:52.988+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T00:22:53.003+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231122T000000, start_date=20231126T002251, end_date=20231126T002253
[2023-11-26T00:22:53.048+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T00:22:53.073+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T01:53:26.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T01:53:26.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T01:53:26.256+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T01:53:26.290+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-22 00:00:00+00:00
[2023-11-26T01:53:26.299+0000] {standard_task_runner.py:57} INFO - Started process 185 to run task
[2023-11-26T01:53:26.304+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpvvbeos4j']
[2023-11-26T01:53:26.310+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask transform
[2023-11-26T01:53:26.427+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T01:53:26.553+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-11-26T01:53:27.361+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T01:53:27.374+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231122T000000, start_date=20231126T015326, end_date=20231126T015327
[2023-11-26T01:53:27.427+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T01:53:27.453+0000] {taskinstance.py:2778} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:44:12.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T02:44:12.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26T02:44:12.257+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T02:44:12.275+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-22 00:00:00+00:00
[2023-11-26T02:44:12.287+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2023-11-26T02:44:12.297+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmph8gs8o3i']
[2023-11-26T02:44:12.304+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask transform
[2023-11-26T02:44:12.386+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:44:12.517+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-11-26T02:44:22.324+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:44:22.338+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231122T000000, start_date=20231126T024412, end_date=20231126T024422
[2023-11-26T02:44:22.388+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:44:22.412+0000] {taskinstance.py:2778} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2023-12-17T15:13:03.099+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-12-17T15:13:03.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-12-17T15:13:03.110+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-17T15:13:03.124+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-22 00:00:00+00:00
[2023-12-17T15:13:03.130+0000] {standard_task_runner.py:57} INFO - Started process 660 to run task
[2023-12-17T15:13:03.134+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpumzser9q']
[2023-12-17T15:13:03.139+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask transform
[2023-12-17T15:13:03.192+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-22T00:00:00+00:00 [running]> on host 7f0547651eb4
[2023-12-17T15:13:03.283+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-12-17T15:13:19.594+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-17T15:13:19.605+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231122T000000, start_date=20231217T151303, end_date=20231217T151319
[2023-12-17T15:13:19.665+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-17T15:13:19.691+0000] {taskinstance.py:2778} INFO - 4 downstream tasks scheduled from follow-on schedule check
