[2023-11-23T22:12:29.695+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T22:12:29.707+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T22:12:29.707+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-23T22:12:29.726+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-23T22:12:29.732+0000] {standard_task_runner.py:57} INFO - Started process 142 to run task
[2023-11-23T22:12:29.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpbkq_sq67']
[2023-11-23T22:12:29.741+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract
[2023-11-23T22:12:29.795+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 3c6bdd9606b4
[2023-11-23T22:12:30.081+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-23T22:12:33.340+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T22:12:33.351+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231123T221229, end_date=20231123T221233
[2023-11-23T22:12:33.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T22:12:33.426+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-24T21:55:13.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-24T21:55:13.282+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-24T21:55:13.283+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T21:55:13.461+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-24T21:55:13.471+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2023-11-24T21:55:13.476+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpyqr7tyi0']
[2023-11-24T21:55:13.480+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract
[2023-11-24T21:55:13.543+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 30eca782d34c
[2023-11-24T21:55:13.646+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-24T21:55:14.566+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/extract.py", line 35, in extract_data
    storage_client = storage.Client('oceanic-hangout-406022')
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 172, in __init__
    super(Client, self).__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/client/__init__.py", line 321, in __init__
    Client.__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/client/__init__.py", line 178, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File opt/***/dags/etl_scripts/oceanic-hangout-406022-fd958fa4d302.json was not found.
[2023-11-24T21:55:14.581+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231124T215513, end_date=20231124T215514
[2023-11-24T21:55:14.597+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task extract (File opt/***/dags/etl_scripts/oceanic-hangout-406022-fd958fa4d302.json was not found.; 209)
[2023-11-24T21:55:14.616+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T21:55:14.637+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-24T23:01:57.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-24T23:01:58.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-24T23:01:58.027+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T23:01:58.070+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-24T23:01:58.079+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-11-24T23:01:58.091+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpfj33epp2']
[2023-11-24T23:01:58.105+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask extract
[2023-11-24T23:01:58.344+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 69a30b58663a
[2023-11-24T23:01:58.690+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-24T23:01:59.938+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-24T23:02:00.165+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231124T230158, end_date=20231124T230200
[2023-11-24T23:02:00.690+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T23:02:00.757+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-25T00:37:35.593+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-25T00:37:35.609+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-25T00:37:35.609+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-25T00:37:35.630+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-25T00:37:35.636+0000] {standard_task_runner.py:57} INFO - Started process 324 to run task
[2023-11-25T00:37:35.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpq7l72byu']
[2023-11-25T00:37:35.644+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask extract
[2023-11-25T00:37:35.705+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 8e76b4343da0
[2023-11-25T00:37:35.795+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-25T00:37:36.668+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T00:37:36.681+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231125T003735, end_date=20231125T003736
[2023-11-25T00:37:36.703+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T00:37:36.730+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-25T20:49:05.845+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-25T20:49:05.860+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-25T20:49:05.861+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-25T20:49:05.878+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-25T20:49:05.883+0000] {standard_task_runner.py:57} INFO - Started process 482 to run task
[2023-11-25T20:49:05.889+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpi6l91p8_']
[2023-11-25T20:49:05.892+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask extract
[2023-11-25T20:49:05.943+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:49:06.028+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-25T20:49:07.092+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T20:49:07.104+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231125T204905, end_date=20231125T204907
[2023-11-25T20:49:07.153+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T20:49:07.178+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:23:05.431+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26T02:23:05.458+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26T02:23:05.458+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-26T02:23:05.477+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-26T02:23:05.484+0000] {standard_task_runner.py:57} INFO - Started process 729 to run task
[2023-11-26T02:23:05.489+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpl5k1i8b5']
[2023-11-26T02:23:05.493+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask extract
[2023-11-26T02:23:05.548+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T02:23:05.642+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-26T02:23:06.740+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:23:06.753+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231126T022305, end_date=20231126T022306
[2023-11-26T02:23:06.795+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:23:06.830+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:50:20.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26T02:50:20.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26T02:50:20.837+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-26T02:50:20.852+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-21 00:00:00+00:00
[2023-11-26T02:50:20.858+0000] {standard_task_runner.py:57} INFO - Started process 416 to run task
[2023-11-26T02:50:20.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpymb_g7cr']
[2023-11-26T02:50:20.865+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask extract
[2023-11-26T02:50:20.917+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-21T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:50:21.004+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-26T02:50:22.097+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:50:22.110+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231121T000000, start_date=20231126T025020, end_date=20231126T025022
[2023-11-26T02:50:22.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:50:22.200+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
